http.host: 0.0.0.0

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1

# x-pack functions
xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.graph.enabled: true
xpack.watcher.enabled: false

# set kuromoji as default Tokenizer
# index.analysis.analyzer.default.type: custom
# index.analysis.analyzer.default.tokenizer: kuromoji_tokenizer
